tests: skip Echo tests when it is not loaded
When Echo is not loaded (it is not required in extension.json), an
integration test will fail:

  1) TheWikipediaLibraryEchoTest::testNoDupes
  Error: Class "MediaWiki\Extension\Notifications\DbFactory" not found

Skip it when Echo is not loaded.

Bug: T410118
Depends-On: Icc71dfe81354cd975c159c85f3cea4967db49b47
Change-Id: If5334c22206933242c895ec5ea377c35c58530ab
(cherry picked from commit cbbabb6150bd39e472d23dbb47999b982958e13b)